services:
  api:
    build: .
    container_name: monitorline
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # default to dev if not set
      - APP_ENV=${APP_ENV:-dev}
    restart: unless-stopped

  worker:
    build: .
    container_name: celery_worker
    command: celery -A app.services.celery worker --loglevel=INFO
    env_file:
      - .env
    depends_on:
      - redis
      - api

  beat:
    build: .
    container_name: celery_beat
    command: celery -A app.services.celery beat --loglevel=INFO
    env_file:
      - .env
    depends_on:
      - redis
      - api
      
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: monitorline
      POSTGRES_PASSWORD: monitorline
      POSTGRES_DB: monitorline
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
